<center>
<img src="https://habrastorage.org/web/677/8e1/337/6778e1337c3d4b159d7e99df94227cb2.jpg"/>
## Специализация "Машинное обучение и анализ данных"
<center>Автор материала: программист-исследователь Mail.Ru Group, старший преподаватель Факультета Компьютерных Наук ВШЭ [Юрий Кашницкий](https://yorko.github.io/)

# <center> Capstone проект №1 <br> Идентификация пользователей по посещенным веб-страницам

<img src='http://i.istockimg.com/file_thumbview_approve/21546327/5/stock-illustration-21546327-identification-de-l-utilisateur.jpg'>

В этом проекте мы будем решать задачу идентификации пользователя по его поведению в сети Интернет. Это сложная и интересная задача на стыке анализа данных и поведенческой психологии. В качестве примера, компания Яндекс решает задачу идентификации взломщика почтового ящика по его поведению. В двух словах, взломщик будет себя вести не так, как владелец ящика: он может не удалять сообщения сразу по прочтении, как это делал хозяин, он будет по-другому ставить флажки сообщениям и даже по-своему двигать мышкой. Тогда такого злоумышленника можно идентифицировать и "выкинуть" из почтового ящика, предложив хозяину войти по SMS-коду. Этот пилотный проект описан в [статье](https://habrahabr.ru/company/yandex/blog/230583/) на Хабрахабре. Похожие вещи делаются, например, в Google Analytics и описываются в научных статьях, найти можно многое по фразам "Traversal Pattern Mining" и "Sequential Pattern Mining".


Мы будем решать похожую задачу: по последовательности из нескольких веб-сайтов, посещенных подряд один и тем же человеком, мы будем идентифицировать этого человека. Идея такая: пользователи Интернета по-разному переходят по ссылкам, и это может помогать их идентифицировать (кто-то сначала в почту, потом про футбол почитать, затем новости, контакт, потом наконец – работать, кто-то – сразу работать).

Будем использовать данные из [статьи](http://ceur-ws.org/Vol-1703/paper12.pdf) "A Tool for Classification of Sequential Data". И хотя мы не можем рекомендовать эту статью (описанные методы делеки от state-of-the-art, лучше обращаться к [книге](http://www.charuaggarwal.net/freqbook.pdf) "Frequent Pattern Mining" и последним статьям с ICDM), но данные там собраны аккуратно и представляют интерес.

Имеются данные с прокси-серверов Университета Блеза Паскаля, они имеют очень простой вид. Для каждого пользователя заведен csv-файл с названием user\*\*\*\*.csv (где вместо звездочек – 4 цифры, соответствующие ID пользователя), а в нем посещения сайтов записаны в следующем формате: <br>

<center>*timestamp, посещенный веб-сайт*</center>

Скачать исходные данные можно по ссылке в статье, там же описание.
Для этого задания хватит данных не по всем 3000 пользователям, а по 10 и 150. [Ссылка](https://drive.google.com/file/d/1AU3M_mFPofbfhFQa_Bktozq_vFREkWJA/view?usp=sharing) на архив *capstone_user_identification* (~7 Mb, в развернутом виде ~ 60 Mb). 

В финальном проекте уже придется столкнуться с тем, что не все операции можно выполнить за разумное время (скажем, перебрать с кросс-валидацией 100 комбинаций параметров случайного леса на этих данных Вы вряд ли сможете), поэтому мы будем использовать параллельно 2 выборки: по 10 пользователям и по 150. Для 10 пользователей будем писать и отлаживать код, для 150 – будет рабочая версия. 

Данные устроены следующем образом:

 - В каталоге 10users лежат 10 csv-файлов с названием вида "user[USER_ID].csv", где [USER_ID] – ID пользователя;
 - Аналогично для каталога 150users – там 150 файлов;
 - В каталоге 3users – игрушечный пример из 3 файлов, это для отладки кода предобработки, который Вы далее напишете.

На 5 неделе будет задание по [соревнованию](https://www.kaggle.com/c/catch-me-if-you-can-intruder-detection-through-webpage-session-tracking2) Kaggle Inclass, которое организовано специально под Capstone проект нашей специализации. Соревнование уже открыто и, конечно, желающие могут начать уже сейчас.

# <center>Неделя 1. Подготовка данных к анализу и построению моделей

Первая часть проекта посвящена подготовке данных для дальнейшего описательного анализа и построения прогнозных моделей. Надо будет написать код для предобработки данных (исходно посещенные веб-сайты указаны для каждого пользователя в отдельном файле) и формирования единой обучающей выборки. Также в этой части мы познакомимся с разреженным форматом данных (матрицы `Scipy.sparse`), который хорошо подходит для данной задачи. 

**План 1 недели:**
 - Часть 1. Подготовка обучающей выборки
 - Часть 2. Работа с разреженным форматом данных

### Задание
1. Заполните код в этой тетрадке 
2. Если вы проходите специализацию Яндеса и МФТИ, пошлите файл с ответами в соответствующем Programming Assignment. <br> Если вы проходите курс ODS, выберите ответы в [веб-форме](https://docs.google.com/forms/d/e/1FAIpQLSedmwHb4cOI32zKJmEP7RvgEjNoz5GbeYRc83qFXVH82KFgGA/viewform). 


**В этой части проекта Вам могут быть полезны видеозаписи следующих лекций 1 и 2 недели курса "Математика и Python для анализа данных":**
   - [Циклы, функции, генераторы, list comprehension](https://www.coursera.org/learn/mathematics-and-python/lecture/Kd7dL/tsikly-funktsii-ghienieratory-list-comprehension)
   - [Чтение данных из файлов](https://www.coursera.org/learn/mathematics-and-python/lecture/8Xvwp/chtieniie-dannykh-iz-failov)
   - [Запись файлов, изменение файлов](https://www.coursera.org/learn/mathematics-and-python/lecture/vde7k/zapis-failov-izmienieniie-failov)
   - [Pandas.DataFrame](https://www.coursera.org/learn/mathematics-and-python/lecture/rcjAW/pandas-data-frame)
   - [Pandas. Индексация и селекция](https://www.coursera.org/learn/mathematics-and-python/lecture/lsXAR/pandas-indieksatsiia-i-sieliektsiia)
   
**Кроме того, в задании будут использоваться библиотеки Python [`glob`](https://docs.python.org/3/library/glob.html), [`pickle`](https://docs.python.org/2/library/pickle.html) и класс [`csr_matrix`](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.sparse.csr_matrix.html) из `Scipy.sparse`.**

Наконец, для лучшей воспроизводимости результатов приведем список версий основных используемых в проекте библиотек: NumPy, SciPy, Pandas, Matplotlib, Statsmodels и Scikit-learn. Для этого воспользуемся расширением [watermark](https://github.com/rasbt/watermark). Рекомендуется использовать докер-контейнер открытого курса OpenDataScience по машинному обучению, инструкции [тут](https://goo.gl/RrwpNd).

In [1]:
1+2

3

In [2]:
# pip install watermark
%load_ext watermark

The watermark extension is already loaded. To reload it, use:
  %reload_ext watermark


In [3]:
%watermark -v -m -p numpy,scipy,pandas,matplotlib,statsmodels,sklearn -g

CPython 2.7.13
IPython 5.3.0

numpy 1.12.1
scipy 0.19.0
pandas 0.20.1
matplotlib 2.0.2
statsmodels 0.8.0
sklearn 0.18.1

compiler   : MSC v.1500 64 bit (AMD64)
system     : Windows
release    : 10
machine    : AMD64
processor  : Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
CPU cores  : 4
interpreter: 64bit
Git hash   :


In [1]:
from __future__ import division, print_function
# отключим всякие предупреждения Anaconda
import warnings
warnings.filterwarnings('ignore')
from glob import glob
import os
import pickle
#pip install tqdm
from tqdm import tqdm_notebook
import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix

**Посмотрим на один из файлов с данными о посещенных пользователем (номер 31) веб-страницах.**

In [2]:
# Поменяйте на свой путь к данным
PATH_TO_DATA = '../data/capstone_user_identification'

In [3]:
user31_data = pd.read_csv(os.path.join(PATH_TO_DATA, 
                                       '10users/user0031.csv'))

In [4]:
sites = {k[0]: (i+1,k[1]) for  i, k in enumerate(user31_data["site"].value_counts().iteritems())}

In [7]:
user31_data.head()

timestamp                        site
0  2013-11-15 08:12:07  fpdownload2.macromedia.com
1  2013-11-15 08:12:17                 laposte.net
2  2013-11-15 08:12:17             www.laposte.net
3  2013-11-15 08:12:17              www.google.com
4  2013-11-15 08:12:18             www.laposte.net

**Поставим задачу классификации: идентифицировать пользователя по сессии из 10 подряд посещенных сайтов. Объектом в этой задаче будет сессия из 10 сайтов, последовательно посещенных одним и тем же пользователем, признаками – индексы этих 10 сайтов (чуть позже здесь появится "мешок" сайтов, подход Bag of Words). Целевым классом будет id пользователя.**

### <center>Пример для иллюстрации</center>
**Пусть пользователя всего 2, длина сессии – 2 сайта.**

<center>user0001.csv</center>
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg .tg-yw4l{vertical-align:top}
</style>
<table class="tg">
  <tr>
    <th class="tg-031e">timestamp</th>
    <th class="tg-031e">site</th>
  </tr>
  <tr>
    <td class="tg-031e">00:00:01</td>
    <td class="tg-031e">vk.com</td>
  </tr>
  <tr>
    <td class="tg-yw4l">00:00:11</td>
    <td class="tg-yw4l">google.com</td>
  </tr>
  <tr>
    <td class="tg-031e">00:00:16</td>
    <td class="tg-031e">vk.com</td>
  </tr>
  <tr>
    <td class="tg-031e">00:00:20</td>
    <td class="tg-031e">yandex.ru</td>
  </tr>
</table>

<center>user0002.csv</center>
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg .tg-yw4l{vertical-align:top}
</style>
<table class="tg">
  <tr>
    <th class="tg-031e">timestamp</th>
    <th class="tg-031e">site</th>
  </tr>
  <tr>
    <td class="tg-031e">00:00:02</td>
    <td class="tg-031e">yandex.ru</td>
  </tr>
  <tr>
    <td class="tg-yw4l">00:00:14</td>
    <td class="tg-yw4l">google.com</td>
  </tr>
  <tr>
    <td class="tg-031e">00:00:17</td>
    <td class="tg-031e">facebook.com</td>
  </tr>
  <tr>
    <td class="tg-031e">00:00:25</td>
    <td class="tg-031e">yandex.ru</td>
  </tr>
</table>

Идем по 1 файлу, нумеруем сайты подряд: vk.com – 1, google.com – 2 и т.д. Далее по второму файлу. 

Отображение сайтов в их индесы должно получиться таким:

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg .tg-yw4l{vertical-align:top}
</style>
<table class="tg">
  <tr>
    <th class="tg-031e">site</th>
    <th class="tg-yw4l">site_id</th>
  </tr>
  <tr>
    <td class="tg-yw4l">vk.com</td>
    <td class="tg-yw4l">1</td>
  </tr>
  <tr>
    <td class="tg-yw4l">google.com</td>
    <td class="tg-yw4l">2</td>
  </tr>
  <tr>
    <td class="tg-yw4l">yandex.ru</td>
    <td class="tg-yw4l">3</td>
  </tr>
  <tr>
    <td class="tg-yw4l">facebook.com</td>
    <td class="tg-yw4l">4</td>
  </tr>
</table>

Тогда обучающая выборка будет такой (целевой признак – user_id):
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg .tg-s6z2{text-align:center}
.tg .tg-baqh{text-align:center;vertical-align:top}
.tg .tg-hgcj{font-weight:bold;text-align:center}
.tg .tg-amwm{font-weight:bold;text-align:center;vertical-align:top}
</style>
<table class="tg">
  <tr>
    <th class="tg-hgcj">session_id</th>
    <th class="tg-hgcj">site1</th>
    <th class="tg-hgcj">site2</th>
    <th class="tg-amwm">user_id</th>
  </tr>
  <tr>
    <td class="tg-s6z2">1</td>
    <td class="tg-s6z2">1</td>
    <td class="tg-s6z2">2</td>
    <td class="tg-baqh">1</td>
  </tr>
  <tr>
    <td class="tg-s6z2">2</td>
    <td class="tg-s6z2">1</td>
    <td class="tg-s6z2">3</td>
    <td class="tg-baqh">1</td>
  </tr>
  <tr>
    <td class="tg-s6z2">3</td>
    <td class="tg-s6z2">3</td>
    <td class="tg-s6z2">2</td>
    <td class="tg-baqh">2</td>
  </tr>
  <tr>
    <td class="tg-s6z2">4</td>
    <td class="tg-s6z2">4</td>
    <td class="tg-s6z2">3</td>
    <td class="tg-baqh">2</td>
  </tr>
</table>

Здесь 1 объект – это сессия из 2 посещенных сайтов 1-ым пользователем (target=1). Это сайты vk.com и google.com (номер 1 и 2). И так далее, всего 4 сессии. Пока сессии у нас не пересекаются по сайтам, то есть посещение каждого отдельного сайта относится только к одной сессии.

## Часть 1. Подготовка обучающей выборки
Реализуйте функцию *prepare_train_set*, которая принимает на вход путь к каталогу с csv-файлами *path_to_csv_files* и параметр *session_length* – длину сессии, а возвращает 2 объекта:
- DataFrame, в котором строки соответствуют уникальным сессиям из *session_length* сайтов, *session_length* столбцов – индексам этих *session_length* сайтов и последний столбец – ID пользователя
- частотный словарь сайтов вида {'site_string': [site_id, site_freq]}, например для недавнего игрушечного примера это будет {'vk.com': (1, 2), 'google.com': (2, 2), 'yandex.ru': (3, 3), 'facebook.com': (4, 1)}

Детали:
- Смотрите чуть ниже пример вывода, что должна возвращать функция
- Используйте `glob` (или аналоги) для обхода файлов в каталоге. Для определенности, отсортируйте список файлов лексикографически. Удобно использовать `tqdm_notebook` (или просто `tqdm` в случае python-скрипта) для отслеживания числа выполненных итераций цикла
- Создайте частотный словарь уникальных сайтов (вида {'site_string': (site_id, site_freq)}) и заполняйте его по ходу чтения файлов. Начните с 1
- Рекомендуется меньшие индексы давать более часто попадающимся сайтам (приницип наименьшего описания)
- Не делайте entity recognition, считайте *google.com*, *http://www.google.com* и *www.google.com* разными сайтами (подключить entity recognition можно уже в рамках индивидуальной работы над проектом)
- Скорее всего в файле число записей не кратно числу *session_length*. Тогда последняя сессия будет короче. Остаток заполняйте нулями. То есть если в файле 24 записи и сессии длины 10, то 3 сессия будет состоять из 4 сайтов, и ей мы сопоставим вектор [*site1_id*, *site2_id*, *site3_id*, *site4_id*, 0, 0, 0, 0, 0, 0, *user_id*] 
- В итоге некоторые сессии могут повторяться – оставьте как есть, не удаляйте дубликаты. Если в двух сессиях все сайты одинаковы, но сессии принадлежат разным пользователям, то тоже оставляйте как есть, это естественная неопределенность в данных
- Не оставляйте в частотном словаре сайт 0 (уже в конце, когда функция возвращает этот словарь)
- 150 файлов из *capstone_websites_data/150users/* у меня обработались за 1.7 секунды, но многое, конечно, зависит от реализации функции и от используемого железа. И вообще, первая реализация скорее всего будет не самой эффективной, дальше можно заняться профилированием (особенно если планируете запускать этот код для 3000 пользователей). Также эффективная реализация этой функции поможет нам на следующей неделе.

In [144]:
!pip install ipdb

  Running setup.py bdist_wheel for ipdb: started
  Running setup.py bdist_wheel for ipdb: finished with status 'done'
  Stored in directory: C:\Users\27C6~1\AppData\Local\pip\Cache\wheels\59\e2\e0\100752b3b9195763fd7f4bcb7b4bfc16c1bd22ab2f07383082
Successfully built ipdb


You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [145]:
from IPython.core.debugger import set_trace

In [5]:
import os
import fnmatch

In [6]:
def prepare_train_set(path_to_csv_files, session_length=10):
    sites = {}
    sitesColumns = ['site%s' % i for i in range(1, session_length+1)]
    sitesColumns.extend(['user_id'])
    resultDf = pd.core.frame.DataFrame(columns=sitesColumns)
    for root, dirnames, filenames in os.walk(path_to_csv_files):
        for filename in tqdm_notebook(fnmatch.filter(filenames, '*.csv')):
            user = int(filename.replace('user','').replace('.csv',''))
            df = pd.read_csv(path_to_csv_files + '/' + filename).sort_values(by=['timestamp'])
            
            dic = {k[0]: (i+1,k[1]) for  i, k in enumerate(df["site"].value_counts().iteritems())}
            for site, value in dic.iteritems():
                if site not in sites:
                    sites[site] = (len(sites)+1,value[1])
                else:
                    curVal=sites[site]
                    sites[site]=(curVal[0],curVal[1]+value[1])
            sessionRow=[]
        
            df["site_id"] = df['site'].apply(lambda ts: sites[ts][0]) 
            arr = np.array(df["site_id"])
            arr = np.append(arr,[0] * ((session_length-df.shape[0]%10)%10))
            
            arr = arr.reshape(int(len(arr) / session_length), session_length)
            b = np.zeros((arr.shape[0],session_length+1))+user
            b[:,:-1] = arr
            
            resultDf = pd.concat([resultDf, pd.DataFrame(b,columns=sitesColumns, dtype=np.int)], axis=0)
    return resultDf, sites

In [7]:
%%time
sites = prepare_train_set(PATH_TO_DATA+'/3users',10)


Wall time: 608 ms


In [173]:
arr = [7 4 4 8 4 2 5 1 6 3 7 2 2 2 0 0 0 0 0 0]
arr = arr.reshape(int(arr / session_length), session_length)

2

In [146]:
user31_data.shape

(7600, 2)

In [150]:
import numpy as np
N = 3
a = np.random.rand(N,N)
b = np.zeros((N,N+1))
b[:,:-1] = a

In [163]:
14/10

1.4

In [153]:
np.zeros((N,N+1))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [132]:
np.array([[1,2], [3, 4], [5, 6]]).flatten().reshape((3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [133]:
np.array([[1,2], [3, 4], [5, 6]]).flatten()

array([1, 2, 3, 4, 5, 6])

In [134]:
b

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [139]:
int('user0001.csv'.replace('user','').replace('.csv',''))

1

In [40]:
type(sites)

NoneType

**Примените полученную функцию к игрушечному примеру, убедитесь, что все работает как надо.**

In [20]:
!cat $PATH_TO_DATA/3users/user0001.csv

timestamp,site
2013-11-15 09:28:17,vk.com
2013-11-15 09:33:04,oracle.com
2013-11-15 09:52:48,oracle.com
2013-11-15 11:37:26,geo.mozilla.org
2013-11-15 11:40:32,oracle.com
2013-11-15 11:40:34,google.com
2013-11-15 11:40:35,accounts.google.com
2013-11-15 11:40:37,mail.google.com
2013-11-15 11:40:40,apis.google.com
2013-11-15 11:41:35,plus.google.com
2013-11-15 12:40:35,vk.com
2013-11-15 12:40:37,google.com
2013-11-15 12:40:40,google.com
2013-11-15 12:41:35,google.com


In [9]:
!cat $PATH_TO_DATA/3users/user0002.csv

timestamp,site
2013-11-15 09:28:17,vk.com
2013-11-15 09:33:04,oracle.com
2013-11-15 09:52:48,football.kulichki.ru
2013-11-15 11:37:26,football.kulichki.ru
2013-11-15 11:40:32,oracle.com


In [10]:
!cat $PATH_TO_DATA/3users/user0003.csv

timestamp,site
2013-11-15 09:28:17,meduza.io
2013-11-15 09:33:04,google.com
2013-11-15 09:52:48,oracle.com
2013-11-15 11:37:26,google.com
2013-11-15 11:40:32,oracle.com
2013-11-15 11:40:34,google.com
2013-11-15 11:40:35,google.com
2013-11-15 11:40:37,mail.google.com
2013-11-15 11:40:40,yandex.ru
2013-11-15 11:41:35,meduza.io
2013-11-15 12:28:17,meduza.io
2013-11-15 12:33:04,google.com
2013-11-15 12:52:48,oracle.com


In [8]:
train_data_toy, site_freq_3users = prepare_train_set(os.path.join(PATH_TO_DATA, '3users'), 
                                                     session_length=10)

In [10]:
train_data_toy

site1 site2 site3 site4 site5 site6 site7 site8 site9 site10 user_id
0     7     4     4     8     4     2     5     1     6      3       1
1     7     2     2     2     0     0     0     0     0      0       1
0     7     4     9     9     4     0     0     0     0      0       2
0    11     2     4     2     4     2     2     1    10     11       3
1    11     2     4     0     0     0     0     0     0      0       3

Частоты сайтов (второй элемент кортежа) точно должны быть такими, нумерация может быть любой (первые элементы кортежей могут отличаться).

Примените полученную функцию к данным по 10 пользователям.

**<font color='red'> Вопрос 1. </font> Сколько уникальных сессий из 10 сайтов в выборке с 10 пользователями?**

In [9]:
%%time
train_data_10users, site_freq_10users = prepare_train_set(os.path.join(PATH_TO_DATA, '10users'), 
                                                     session_length=10)


Wall time: 2.32 s


In [269]:
sessions = train_data_10users[['site%s' % i for i in range(1, 10+1)]].copy()

In [259]:
 sessions['site_ids_ordered'] = sessions[site_columns].apply(lambda row: np.array2string(np.sort(np.array(row)), separator='_'), axis=1) 

In [260]:
sessions.head()

site1 site2 site3 site4 site5 site6 site7 site8 site9 site10  \
0   583   530   743   536   743   743   536   743   722    743   
1   429   468   624   466   743   913    15   434   320    643   
2   643   536   643   643    45   291   429   151   334    643   
3   664    17   664   643   643   643   643   810   841      1   
4   882   643    45   324   552   200   257   657   791    657   

                            site_ids_ordered  site_ids_ordered3  
0  [530_536_536_583_722_743_743_743_743_743]                NaN  
1   [15_320_429_434_466_468_624_643_743_913]                NaN  
2   [45_151_291_334_429_536_643_643_643_643]                NaN  
3     [1_17_643_643_643_643_664_664_810_841]                NaN  
4   [45_200_257_324_552_643_657_657_791_882]                NaN

In [265]:
sessions['site_ids_ordered'].value_counts().shape

(12049L,)

In [226]:
site_columns = ['site%s' % i for i in range(1, 10+1)]

In [237]:
np.array(sessions[site_columns].iloc[0]).sum()

6622

In [270]:
uiqu_sessions = sessions.drop_duplicates()

In [271]:
len(uiqu_sessions)

13181

In [56]:
len(uiqu_sessions)

13181

In [49]:
uiqu_sessions.head()

site1 site2 site3 site4 site5 site6 site7 site8 site9 site10
0     1     2     3     4     3     3     4     3     5      3
1     6     7     8     9     3    10    11    12    13     14
2    14     4    14    14    15    16     6    17    18     14
3    19    20    19    14    14    14    14    21    22     23
4    24    14    15    25    26    27    28    29    30     29

In [266]:
sessions.shape

(14061, 12)

**<font color='red'> Вопрос 2. </font> Сколько всего уникальных сайтов в выборке из 10 пользователей? **

In [272]:
len(site_freq_10users)

4913

In [10]:
%%time
train_data_10users, site_freq_10users = prepare_train_set(os.path.join(PATH_TO_DATA, '10users'), 
                                                     session_length=10)


Wall time: 1.1 s


Примените полученную функцию к данным по 150 пользователям.

**<font color='red'> Вопрос 3. </font> Сколько уникальных сессий из 10 сайтов в выборке с 150 пользователями?**

In [11]:
%%time
train_data_150users, site_freq_150users = prepare_train_set(os.path.join(PATH_TO_DATA, '150users'), 
                                                     session_length=10)


Wall time: 23.2 s


In [276]:
train_data_150users.shape

(137019, 11)

In [277]:
len(site_freq_150users)

27797

In [285]:
sorted(site_freq_150users.iteritems(), cmp=None, key=lambda x: x[1][1], reverse=True)[:10]

[('www.google.fr', (329, 64785)),
 ('www.google.com', (297, 51320)),
 ('www.facebook.com', (355, 39002)),
 ('apis.google.com', (156, 29983)),
 ('s.youtube.com', (248, 29102)),
 ('clients1.google.com', (346, 25087)),
 ('mail.google.com', (71, 19072)),
 ('plus.google.com', (111, 18467)),
 ('safebrowsing-cache.google.com', (303, 17960)),
 ('www.youtube.com', (441, 16319))]

**<font color='red'> Вопрос 4. </font> Сколько всего уникальных сайтов в выборке из 150 пользователей? **

In [ ]:
''' ВАШ КОД ЗДЕСЬ '''

**<font color='red'> Вопрос 5. </font> Какой из этих сайтов НЕ входит в топ-10 самых популярных сайтов среди посещенных 150 пользователями?**
- www.google.fr
- www.youtube.com
- safebrowsing-cache.google.com
- www.linkedin.com

In [ ]:
''' ВАШ КОД ЗДЕСЬ '''

**Для дальнейшего анализа запишем полученные объекты DataFrame в csv-файлы.**

In [12]:
train_data_10users.to_csv(os.path.join(PATH_TO_DATA, 
                                       'train_data_10users.csv'), 
                        index_label='session_id', float_format='%d')
train_data_150users.to_csv(os.path.join(PATH_TO_DATA, 
                                        'train_data_150users.csv'), 
                         index_label='session_id', float_format='%d')

## Часть 2. Работа с разреженным форматом данных

Если так подумать, то полученные признаки *site1*, ..., *site10* смысла не имеют как признаки в задаче классификации. А вот если воспользоваться идеей мешка слов из анализа текстов – это другое дело. Создадим новые матрицы, в которых строкам будут соответствовать сессии из 10 сайтов, а столбцам – индексы сайтов. На пересечении строки $i$ и столбца $j$ будет стоять число $n_{ij}$ – cколько раз сайт $j$ встретился в сессии номер $i$. Делать это будем с помощью разреженных матриц Scipy – [csr_matrix](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.sparse.csr_matrix.html). Прочитайте документацию, разберитесь, как использовать разреженные матрицы и создайте такие матрицы для наших данных. Сначала проверьте на игрушечном примере, затем примените для 10 и 150 пользователей. 

Обратите внимание, что в коротких сессиях, меньше 10 сайтов, у нас остались нули, так что первый признак (сколько раз попался 0) по смыслу отличен от остальных (сколько раз попался сайт с индексом $i$). Поэтому первый столбец разреженной матрицы надо будет удалить. 

In [25]:
len(site_freq_3users)

11

In [22]:
train_data_toy.shape

(5, 11)

In [27]:
X_sparse_toy = csr_matrix((train_data_toy.shape[0], len(site_freq_3users)), dtype=np.int8)

In [13]:
sitesColumns = ['site%s' % i for i in range(1, 11)]

In [106]:
train_data_toy.iloc[0][sitesColumns].values

array([7, 4, 4, 8, 4, 2, 5, 1, 6, 3], dtype=object)

In [120]:
(train_data_toy.iloc[0][sitesColumns].value_counts())

4    3
8    1
7    1
6    1
5    1
3    1
2    1
1    1
Name: 0, dtype: int64

In [78]:
sum([x == 84 for x in train_data_toy.iloc[0][sitesColumns].values])

0

In [44]:
site_freq_3users

{'accounts.google.com': (5, 1),
 'apis.google.com': (6, 1),
 'football.kulichki.ru': (9, 2),
 'geo.mozilla.org': (8, 1),
 'google.com': (2, 9),
 'mail.google.com': (1, 2),
 'meduza.io': (11, 3),
 'oracle.com': (4, 8),
 'plus.google.com': (3, 1),
 'vk.com': (7, 3),
 'yandex.ru': (10, 1)}

In [104]:
  
#           dic = {k[0]: (i+1,k[1]) for  i, k in enumerate(df["site"].value_counts().iteritems())}
for site, value in site_freq_3users.iteritems():
    i = 0
    for idx, row in train_data_toy.iterrows():
        X_sparse_toy[i,value[0]-1] = sum([x == value[0] for x in row[sitesColumns].values])
#        print(i)
#        print(value[0])
        i =i+1
#        print(len(row[1][sitesColumns]== site[0]))

In [121]:
X_sparse_toy.shape

(5, 11)

In [131]:
X_sparse_toy3 = csr_matrix((train_data_toy.shape[0], len(site_freq_3users)), dtype=np.int8)

In [132]:
i=0
for idx, row in train_data_toy.iterrows():
    for id, count in row[sitesColumns].value_counts().iteritems():
        if id==0:
            continue
 #       print(id)
 #       print(count)
        X_sparse_toy3[i,id-1] = count
    i=i+1

In [133]:
X_sparse_toy3.todense()

matrix([[1, 1, 1, 3, 1, 1, 1, 1, 0, 0, 0],
        [0, 3, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 2, 0, 0, 1, 0, 2, 0, 0],
        [1, 4, 0, 2, 0, 0, 0, 0, 0, 1, 2],
        [0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1]], dtype=int8)

In [125]:
X_sparse_toy.todense()

matrix([[1, 1, 1, 3, 1, 1, 1, 1, 1, 0, 0],
        [6, 3, 3, 0, 0, 0, 1, 1, 0, 0, 6],
        [5, 0, 0, 2, 2, 0, 1, 1, 2, 2, 5],
        [1, 4, 4, 2, 2, 0, 0, 0, 0, 1, 2],
        [0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1]], dtype=int8)

In [91]:
X_sparse_toy.todense()

matrix([[1, 1, 1, 3, 1, 1, 1, 1, 0, 0, 0],
        [0, 3, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 2, 0, 0, 1, 0, 2, 0, 0],
        [1, 4, 0, 2, 0, 0, 0, 0, 0, 1, 2],
        [0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1]], dtype=int8)

In [89]:
train_data_toy

site1 site2 site3 site4 site5 site6 site7 site8 site9 site10 user_id
0     7     4     4     8     4     2     5     1     6      3       1
1     7     2     2     2     0     0     0     0     0      0       1
0     7     4     9     9     4     0     0     0     0      0       2
0    11     2     4     2     4     2     2     1    10     11       3
1    11     2     4     0     0     0     0     0     0      0       3

In [13]:
X_toy, y_toy = train_data_toy.iloc[:, :-1].values, train_data_toy.iloc[:, -1].values

In [14]:
X_toy

array([[7, 4, 4, 8, 4, 2, 5, 1, 6, 3],
       [7, 2, 2, 2, 0, 0, 0, 0, 0, 0],
       [7, 4, 9, 9, 4, 0, 0, 0, 0, 0],
       [11, 2, 4, 2, 4, 2, 2, 1, 10, 11],
       [11, 2, 4, 0, 0, 0, 0, 0, 0, 0]], dtype=object)

**Размерность разреженной матрицы должна получиться равной 11, поскольку в игрушечном примере 3 пользователя посетили 11 уникальных сайтов.**

In [87]:
X_sparse_toy.todense()

matrix([[0, 1, 1, 1, 3, 1, 1, 1, 1, 0, 0],
        [6, 0, 3, 0, 0, 0, 0, 1, 0, 0, 0],
        [5, 0, 0, 0, 2, 0, 0, 1, 0, 2, 0],
        [0, 1, 4, 0, 2, 0, 0, 0, 0, 0, 1],
        [7, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [21]:
X_sparse_toy.todense()

matrix([[1, 3, 1, 0, 1, 0, 1, 1, 1, 1, 0],
        [3, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 2, 1, 0, 0, 2, 0, 0, 0, 0, 0],
        [4, 2, 0, 2, 1, 0, 0, 0, 0, 0, 1],
        [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0]])

In [92]:
X_10users, y_10users = train_data_10users.iloc[:, :-1].values, \
                       train_data_10users.iloc[:, -1].values
X_150users, y_150users = train_data_150users.iloc[:, :-1].values, \
                         train_data_150users.iloc[:, -1].values

In [95]:
X_sparse_10users = csr_matrix((train_data_10users.shape[0], len(site_freq_10users)), dtype=np.int8)

In [96]:
i = 0
for site, value in site_freq_10users.iteritems():
    i = 0
    for idx, row in train_data_10users.iterrows():
        X_sparse_10users[i,value[0]-1] = sum([x == value[0] for x in row[sitesColumns].values])
#        print(i)
#        print(value[0])
        i =i+1

KeyboardInterrupt: 

In [14]:
X_sparse_10users = csr_matrix((train_data_10users.shape[0], len(site_freq_10users)), dtype=np.int8)
i=0
for idx, row in tqdm_notebook(train_data_10users.iterrows()):
    for id, count in row[sitesColumns].value_counts().iteritems():
        if id==0:
            continue
 #       print(id)
 #       print(count)
        X_sparse_10users[i,id-1] = count
    i=i+1

In [138]:
train_data_150users.shape

(137019, 11)

In [ ]:
X_sparse_150users = csr_matrix((train_data_150users.shape[0], len(site_freq_150users)), dtype=np.int8)
i=0
for idx, row in tqdm_notebook(train_data_150users.iterrows()):
    for id, count in row[sitesColumns].value_counts().iteritems():
        if id==0:
            continue
 #       print(id)
 #       print(count)
        X_sparse_150users[i,id-1] = count
    i=i+1

In [ ]:
X_sparse_10users = ''' ВАШ КОД ЗДЕСЬ '''
X_sparse_150users = ''' ВАШ КОД ЗДЕСЬ '''

**Сохраним эти разреженные матрицы с помощью [pickle](https://docs.python.org/2/library/pickle.html) (сериализация в Python), также сохраним вектора *y_10users, y_150users* – целевые значения (id пользователя)  в выборках из 10 и 150 пользователей. То что названия этих матриц начинаются с X и y, намекает на то, что на этих данных мы будем проверять первые модели классификации.
Наконец, сохраним также и частотные словари сайтов для 3, 10 и 150 пользователей.**

In [17]:
train_data_10users.head()

site1 site2 site3 site4 site5 site6 site7 site8 site9 site10 user_id
0   584   530   744   536   744   744   536   744   723    744      31
1   430   469   625   467   913   744    15   435   317    644      31
2   644   536   644   644    43   287   430   665   644    331      31
3   147    17   665   644   644   644   644   811   842      1      31
4   883   644    43   845   553   195   252   658   792    658      31

In [18]:
y_10users = train_data_10users.user_id

In [19]:
with open(os.path.join(PATH_TO_DATA, 'X_sparse_10users.pkl'), 'wb') as X10_pkl:
    pickle.dump(X_sparse_10users, X10_pkl, protocol=2)
with open(os.path.join(PATH_TO_DATA, 'y_10users.pkl'), 'wb') as y10_pkl:
    pickle.dump(y_10users, y10_pkl, protocol=2)
with open(os.path.join(PATH_TO_DATA, 'site_freq_3users.pkl'), 'wb') as site_freq_3users_pkl:
    pickle.dump(site_freq_3users, site_freq_3users_pkl, protocol=2)
with open(os.path.join(PATH_TO_DATA, 'site_freq_10users.pkl'), 'wb') as site_freq_10users_pkl:
    pickle.dump(site_freq_10users, site_freq_10users_pkl, protocol=2)

In [ ]:
with open(os.path.join(PATH_TO_DATA, 'X_sparse_10users.pkl'), 'wb') as X10_pkl:
    pickle.dump(X_sparse_10users, X10_pkl, protocol=2)
with open(os.path.join(PATH_TO_DATA, 'y_10users.pkl'), 'wb') as y10_pkl:
    pickle.dump(y_10users, y10_pkl, protocol=2)
with open(os.path.join(PATH_TO_DATA, 'X_sparse_150users.pkl'), 'wb') as X150_pkl:
    pickle.dump(X_sparse_150users, X150_pkl, protocol=2)
with open(os.path.join(PATH_TO_DATA, 'y_150users.pkl'), 'wb') as y150_pkl:
    pickle.dump(y_150users, y150_pkl, protocol=2)
with open(os.path.join(PATH_TO_DATA, 'site_freq_3users.pkl'), 'wb') as site_freq_3users_pkl:
    pickle.dump(site_freq_3users, site_freq_3users_pkl, protocol=2)
with open(os.path.join(PATH_TO_DATA, 'site_freq_10users.pkl'), 'wb') as site_freq_10users_pkl:
    pickle.dump(site_freq_10users, site_freq_10users_pkl, protocol=2)
with open(os.path.join(PATH_TO_DATA, 'site_freq_150users.pkl'), 'wb') as site_freq_150users_pkl:
    pickle.dump(site_freq_150users, site_freq_150users_pkl, protocol=2)

**Чисто для подстраховки проверим, что число столбцов в разреженных матрицах `X_sparse_10users` и `X_sparse_150users` равно ранее посчитанным числам уникальных сайтов для 10 и 150 пользователей соответственно.**

In [15]:
assert X_sparse_10users.shape[1] == len(site_freq_10users)

In [137]:
X_sparse_10users.shape

(14061, 4913)

In [ ]:
assert X_sparse_150users.shape[1] == len(site_freq_150users)

## Пути улучшения
-  можно обработать исходные данные по 3000 пользователей; обучать на такой выборке модели лучше при наличии доступа к хорошим мощностям (можно арендовать инстанс Amazon EC2, как именно, описано [тут](https://habrahabr.ru/post/280562/)). Хотя далее в курсе мы познакомимся с алгоритмами, способными обучаться на больших выборках при малых вычислительных потребностях;
- помимо явного создания разреженного формата можно еще составить выборки с помощью `CountVectorizer`, `TfidfVectorizer` и т.п. Поскольку данные по сути могут быть описаны как последовательности, то можно вычислять n-граммы сайтов. Работает все это или нет, мы будем проверять в [соревновании](https://inclass.kaggle.com/c/catch-me-if-you-can-intruder-detection-through-webpage-session-tracking2) Kaggle Inclass (желающие могут начать уже сейчас).

На следующей неделе мы еще немного поготовим данные и потестируем первые гипотезы, связанные с нашими наблюдениями. 